services:
  rowsplit:
    build: .
    expose:
      - "5000"
    env_file: .env
    volumes:
      - rowsplit_data:/app/data
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80" # Map standard HTTP
      - "443:443" # Map standard HTTPS for SSL
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - rowsplit

volumes:
  rowsplit_data:
