server {
    listen 80;
    server_name rowalyse.rubenvlieger.nl;
    return 301 https://$host$request_uri; # Force HTTPS 
}

server {
    listen 443 ssl;
    server_name rowalyse.rubenvlieger.nl; [cite: 164]

    ssl_certificate /etc/letsencrypt/live/rowalyse.rubenvlieger.nl/fullchain.pem; 
    ssl_certificate_key /etc/letsencrypt/live/rowalyse.rubenvlieger.nl/privkey.pem; 

    location / {
        proxy_pass http://rowsplit:5000; 
        proxy_set_header Host $host; [cite: 165]
        proxy_set_header X-Real-IP $remote_addr; [cite: 165]
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; [cite: 165]
        proxy_set_header X-Forwarded-Proto https; [cite: 165]
    }
}